---
version: "2.1"
services:
  webtopxfc:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop-ubuntu-xfce
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TITLE=Webtop #optional
    volumes:
      - /home/azureuser/webtop/xfce:/config
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
  
  webtopkde:
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    container_name: webtop-ubuntu-kde
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - /home/azureuser/webtop/kde:/config
    ports:
      - 3100:3000
      - 3101:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped

  webtopmate:
    image: lscr.io/linuxserver/webtop:ubuntu-mate
    container_name: webtop-ubuntu-mate
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - /home/azureuser/webtop/mate:/config
    ports:
      - 3200:3000
      - 3201:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
